object Versions {
    const val sharedElement = "0.1.0-SNAPSHOT"
    const val activityCompose= "1.3.1"
    const val lifeCycle= "1.0.0-alpha07"
    const val compose= "1.0.5"
    const val composeCompiler = "1.4.0"
    const val navigation = "2.5.3"
    const val coroutine = "1.3.9"
    const val multiDex = "2.0.1"
    const val ktor= "1.6.7"
    const val androidTools= "7.1.0"
    const val kotlin = "1.8.0"
    const val material = "1.4.0"
    const val appCompat = "1.4.0"
    const val ktx = "1.7.0"
    const val dagger = "2.44.2"
    const val daggerNavCompose = "1.0.0"
    const val glide = "1.4.7"
    const val coil = "2.2.2"
}